// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjt4OgD0_NfKwGkogt51D0flNRrisiSFI',
    appId: '1:665031879469:web:8162d1d4fe343b392d41a4',
    messagingSenderId: '665031879469',
    projectId: 'powerupdata-a13dc',
    authDomain: 'powerupdata-a13dc.firebaseapp.com',
    storageBucket: 'powerupdata-a13dc.appspot.com',
    measurementId: 'G-2JNQJTBWFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIHuGUfIX1q1-cylT9rskmxVlrcLX59NI',
    appId: '1:665031879469:android:d27c56d2a8345dfa2d41a4',
    messagingSenderId: '665031879469',
    projectId: 'powerupdata-a13dc',
    storageBucket: 'powerupdata-a13dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNApGZwutbouCY--XMv4OLLHtY2DO2eeE',
    appId: '1:665031879469:ios:6b019bc25879d9d52d41a4',
    messagingSenderId: '665031879469',
    projectId: 'powerupdata-a13dc',
    storageBucket: 'powerupdata-a13dc.appspot.com',
    iosBundleId: 'com.example.powerupdata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNApGZwutbouCY--XMv4OLLHtY2DO2eeE',
    appId: '1:665031879469:ios:6b019bc25879d9d52d41a4',
    messagingSenderId: '665031879469',
    projectId: 'powerupdata-a13dc',
    storageBucket: 'powerupdata-a13dc.appspot.com',
    iosBundleId: 'com.example.powerupdata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjt4OgD0_NfKwGkogt51D0flNRrisiSFI',
    appId: '1:665031879469:web:71af75d86d639d022d41a4',
    messagingSenderId: '665031879469',
    projectId: 'powerupdata-a13dc',
    authDomain: 'powerupdata-a13dc.firebaseapp.com',
    storageBucket: 'powerupdata-a13dc.appspot.com',
    measurementId: 'G-66Z1FYWXF8',
  );
}
